package lt.vinco.ebdimport.entity;
// Generated Sep 13, 2012 10:00:03 AM by Hibernate Tools 3.2.1.GA



/**
 * HistoryId generated by hbm2java
 */
public class HistoryId  implements java.io.Serializable {


     private String idappli;
     private Short odhisto;

    public HistoryId() {
    }

    public HistoryId(String idappli, Short odhisto) {
       this.idappli = idappli;
       this.odhisto = odhisto;
    }
   
    public String getIdappli() {
        return this.idappli;
    }
    
    public void setIdappli(String idappli) {
        this.idappli = idappli;
    }
    public Short getOdhisto() {
        return this.odhisto;
    }
    
    public void setOdhisto(Short odhisto) {
        this.odhisto = odhisto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HistoryId) ) return false;
		 HistoryId castOther = ( HistoryId ) other; 
         
		 return ( (this.getIdappli()==castOther.getIdappli()) || ( this.getIdappli()!=null && castOther.getIdappli()!=null && this.getIdappli().equals(castOther.getIdappli()) ) )
 && ( (this.getOdhisto()==castOther.getOdhisto()) || ( this.getOdhisto()!=null && castOther.getOdhisto()!=null && this.getOdhisto().equals(castOther.getOdhisto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdappli() == null ? 0 : this.getIdappli().hashCode() );
         result = 37 * result + ( getOdhisto() == null ? 0 : this.getOdhisto().hashCode() );
         return result;
   }   


}


