package lt.vinco.ebdimport.entity;
// Generated Sep 13, 2012 10:00:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History  implements java.io.Serializable {


     private HistoryId id;
     private String idoper;
     private Date dtoper;
     private String oldinfo;
     private String rmhisto;
     private short sthisto;
     private Short iduseroper;
     private Short cddecioper;
     private Date dtdecioper;
     private Short stpay;
     private Date dtlegal;
     private Date dtaction;
     private Short lvlpubli;
     private Integer idgenbefore;
     private Integer idgenafter;
     private int gengen;

    public History() {
    }

	
    public History(HistoryId id, String idoper, Date dtoper, short sthisto, int gengen) {
        this.id = id;
        this.idoper = idoper;
        this.dtoper = dtoper;
        this.sthisto = sthisto;
        this.gengen = gengen;
    }
    public History(HistoryId id, String idoper, Date dtoper, String oldinfo, String rmhisto, short sthisto, Short iduseroper, Short cddecioper, Date dtdecioper, Short stpay, Date dtlegal, Date dtaction, Short lvlpubli, Integer idgenbefore, Integer idgenafter, int gengen) {
       this.id = id;
       this.idoper = idoper;
       this.dtoper = dtoper;
       this.oldinfo = oldinfo;
       this.rmhisto = rmhisto;
       this.sthisto = sthisto;
       this.iduseroper = iduseroper;
       this.cddecioper = cddecioper;
       this.dtdecioper = dtdecioper;
       this.stpay = stpay;
       this.dtlegal = dtlegal;
       this.dtaction = dtaction;
       this.lvlpubli = lvlpubli;
       this.idgenbefore = idgenbefore;
       this.idgenafter = idgenafter;
       this.gengen = gengen;
    }
   
    public HistoryId getId() {
        return this.id;
    }
    
    public void setId(HistoryId id) {
        this.id = id;
    }
    public String getIdoper() {
        return this.idoper;
    }
    
    public void setIdoper(String idoper) {
        this.idoper = idoper;
    }
    public Date getDtoper() {
        return this.dtoper;
    }
    
    public void setDtoper(Date dtoper) {
        this.dtoper = dtoper;
    }
    public String getOldinfo() {
        return this.oldinfo;
    }
    
    public void setOldinfo(String oldinfo) {
        this.oldinfo = oldinfo;
    }
    public String getRmhisto() {
        return this.rmhisto;
    }
    
    public void setRmhisto(String rmhisto) {
        this.rmhisto = rmhisto;
    }
    public short getSthisto() {
        return this.sthisto;
    }
    
    public void setSthisto(short sthisto) {
        this.sthisto = sthisto;
    }
    public Short getIduseroper() {
        return this.iduseroper;
    }
    
    public void setIduseroper(Short iduseroper) {
        this.iduseroper = iduseroper;
    }
    public Short getCddecioper() {
        return this.cddecioper;
    }
    
    public void setCddecioper(Short cddecioper) {
        this.cddecioper = cddecioper;
    }
    public Date getDtdecioper() {
        return this.dtdecioper;
    }
    
    public void setDtdecioper(Date dtdecioper) {
        this.dtdecioper = dtdecioper;
    }
    public Short getStpay() {
        return this.stpay;
    }
    
    public void setStpay(Short stpay) {
        this.stpay = stpay;
    }
    public Date getDtlegal() {
        return this.dtlegal;
    }
    
    public void setDtlegal(Date dtlegal) {
        this.dtlegal = dtlegal;
    }
    public Date getDtaction() {
        return this.dtaction;
    }
    
    public void setDtaction(Date dtaction) {
        this.dtaction = dtaction;
    }
    public Short getLvlpubli() {
        return this.lvlpubli;
    }
    
    public void setLvlpubli(Short lvlpubli) {
        this.lvlpubli = lvlpubli;
    }
    public Integer getIdgenbefore() {
        return this.idgenbefore;
    }
    
    public void setIdgenbefore(Integer idgenbefore) {
        this.idgenbefore = idgenbefore;
    }
    public Integer getIdgenafter() {
        return this.idgenafter;
    }
    
    public void setIdgenafter(Integer idgenafter) {
        this.idgenafter = idgenafter;
    }
    public int getGengen() {
        return this.gengen;
    }
    
    public void setGengen(int gengen) {
        this.gengen = gengen;
    }




}


